<?php

namespace Database\Seeders;

use App\Models\Cause;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CausesSeeder extends Seeder
{
    public function run()
    {
        $causes = [
            [
                'title' => 'توفير وجبات إفطار لـ 1000 أسرة في رمضان',
                'description' => 'نسعى لتوفير وجبات إفطار يومية خلال شهر رمضان المبارك للأسر المحتاجة في المناطق النائية.',
                'category' => 'إغاثة غذائية',
                'location' => 'عمان - جبل النصر',
                'goal_amount' => 10000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(2),
                'user_id' => 1,
                'additional_details' => 'يشمل المشروع توزيع 30 ألف وجبة على مدار الشهر',
                'responsible_person_name' => 'أحمد محمد',
                'responsible_person_email' => 'ahmed@charity.org',
                'image' => 'causes/ramadan-food.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'بناء بئر ماء في قرية نائية',
                'description' => 'تمويل حفر بئر ماء وتجهيزه بمضخة تعمل بالطاقة الشمسية لقرية تعاني من نقص المياه الصالحة للشرب.',
                'category' => 'مشاريع مائية',
                'location' => 'الزرقاء - منطقة الرصيفة',
                'goal_amount' => 5000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(6),
                'user_id' => 1,
                'additional_details' => 'سيسهم المشروع في توفير مياه نظيفة لأكثر من 500 شخص',
                'responsible_person_name' => 'سارة عبدالله',
                'responsible_person_email' => 'sara@charity.org',
                'image' => 'causes/water-well.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'تجهيز 50 طالبًا بمستلزمات مدرسية',
                'description' => 'توفير الحقائب المدرسية والكتب والأدوات الكتابية لطلاب الأسر غير القادرة.',
                'category' => 'التعليم',
                'location' => 'إربد - مخيم الحصن',
                'goal_amount' => 2500,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonth(),
                'user_id' => 1,
                'additional_details' => 'يشمل كل حقيبة: كتب، دفاتر، أدوات قرطاسية كاملة',
                'responsible_person_name' => 'محمد خالد',
                'responsible_person_email' => 'mohamed@charity.org',
                'image' => 'causes/school-supplies.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'علاج طفل مصاب بمرض نادر',
                'description' => 'مساعدة طفل عمره 6 سنوات في الحصول على العلاج المناسب لمرض نادر يعاني منه.',
                'category' => 'الرعاية الصحية',
                'location' => 'البلقاء - السلط',
                'goal_amount' => 15000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(3),
                'user_id' => 2,
                'additional_details' => 'التكاليف تشمل العلاج والأدوية والمتابعة الطبية',
                'responsible_person_name' => 'ليلى مصطفى',
                'responsible_person_email' => 'layla@charity.org',
                'image' => 'causes/sick-child.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'كفالة 10 أيتام لمدة عام',
                'description' => 'توفير الرعاية الشاملة (تعليم، صحة، سكن، غذاء) لعشرة أطفال يتامى لمدة عام كامل.',
                'category' => 'كفالة الأيتام',
                'location' => 'مأدبا - مدينة مأدبا',
                'goal_amount' => 12000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addYear(),
                'user_id' => 3,
                'additional_details' => 'يشمل المشروع الرعاية التعليمية والصحية والسكنية',
                'responsible_person_name' => 'عمر فاروق',
                'responsible_person_email' => 'omar@charity.org',
                'image' => 'causes/orphans.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'مساعدة الأسر المتضررة من البرد القارس',
                'description' => 'توفير المساعدات العاجلة (دفايات، بطانيات، أغذية) للأسر المتضررة من موجة البرد القارس.',
                'category' => 'الإغاثة الطارئة',
                'location' => 'الكرك - القصر',
                'goal_amount' => 20000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(4),
                'user_id' => 3,
                'additional_details' => 'الهدف مساعدة 500 أسرة متضررة',
                'responsible_person_name' => 'نورا أحمد',
                'responsible_person_email' => 'nora@charity.org',
                'image' => 'causes/winter-aid.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'توفير سكن مؤقت للأسر النازحة',
                'description' => 'بناء وحدات سكنية مؤقتة للأسر التي نزحت بسبب الظروف الاقتصادية الصعبة.',
                'category' => 'الإسكان',
                'location' => 'معان - مدينة معان',
                'goal_amount' => 18000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(5),
                'user_id' => 4,
                'additional_details' => 'سيتم بناء 30 وحدة سكنية مجهزة بمرافق أساسية',
                'responsible_person_name' => 'خالد وليد',
                'responsible_person_email' => 'khaled@charity.org',
                'image' => 'causes/housing.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'برنامج تعليمي للأطفال المحتاجين',
                'description' => 'إنشاء مركز تعليمي يوفر التعليم الأساسي للأطفال المحتاجين في المناطق النائية.',
                'category' => 'التعليم',
                'location' => 'العقبة - منطقة القويرة',
                'goal_amount' => 8000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(3),
                'user_id' => 4,
                'additional_details' => 'سيستفيد من المركز 150 طفلاً',
                'responsible_person_name' => 'ريماس علي',
                'responsible_person_email' => 'reemas@charity.org',
                'image' => 'causes/education.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'دعم الأسر المنتجة',
                'description' => 'تمويل مشاريع صغيرة للأسر المنتجة لتمكينهم اقتصادياً.',
                'category' => 'التنمية الاقتصادية',
                'location' => 'جرش - مدينة جرش',
                'goal_amount' => 15000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(6),
                'user_id' => 2,
                'additional_details' => 'يشمل 20 مشروعاً صغيراً',
                'responsible_person_name' => 'سامي راشد',
                'responsible_person_email' => 'sami@charity.org',
                'image' => 'causes/economic-projects.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'عيادة طبية متنقلة',
                'description' => 'توفير عيادة طبية متنقلة تقدم خدمات صحية مجانية في المناطق النائية.',
                'category' => 'الرعاية الصحية',
                'location' => 'الطفيلة - بصيرا',
                'goal_amount' => 25000,
                'raised_amount' => 0,
                'end_date' => Carbon::now()->addMonths(8),
                'user_id' => 3,
                'additional_details' => 'ستخدم العيادة أكثر من 3000 شخص سنوياً',
                'responsible_person_name' => 'د. ياسر الحمود',
                'responsible_person_email' => 'yasser@charity.org',
                'image' => 'causes/mobile-clinic.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        foreach ($causes as $cause) {
            Cause::create($cause);
        }
    }
}
